Fix typos in documentation
clue/reactphp-tar pull request #20
Opened 2024-01-17 08:57 UTC by yadaiio

This pull request fixes a few typos with the help of https://github.com/szepeviktor/typos-on-you.

2024-01-22 06:21 UTC, SimonFrings approved these changes
Looks good to me :+1:

2024-01-26 10:14 UTC, SimonFrings requested changes
Thanks for updating this PR, added a few remarks below :+1:

These changes look similar to https://github.com/clue/reactphp-sqlite/pull/43, maybe include a reference to this ticket in your description and update the title?

2024-01-26 10:14 UTC, SimonFrings commented on README.md
> +$stream = new React/Stream/ReadableResourceStream(fopen('archive.tar', 'r'));
You're currently using the wrong slashes in here, I added a suggested change below. My suggestions also aligns with PSR-4, maybe worth to take a look at https://www.php-fig.org/psr/psr-4/ 

```suggestion
$stream = new React\Stream\ReadableResourceStream(fopen('archive.tar', 'r'));
```

2024-01-26 10:14 UTC, SimonFrings commented on README.md
> +$decoder = new Clue/React/Tar/Decoder();
You're currently using the wrong slashes in here, I added a suggested change below. My suggestions also aligns with PSR-4, maybe worth to take a look at https://www.php-fig.org/psr/psr-4/ 

```suggestion
$decoder = new Clue\React\Tar\Decoder();
```

2024-01-26 10:23 UTC, yadaiio commented
Thank you @SimonFrings for informing me about this. Changes should be okay by now, I also changed the title of this pull request and added the references. Thank you 👍

2024-01-26 13:56 UTC, SimonFrings approved these changes
Looks good to me :+1:

2024-02-03 21:50 UTC, clue approved these changes
@yadaiio Thanks for looking into this, changes LGTM! :shipit:

2024-02-03 21:50 UTC, merged